src/Entity/Personne.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\BlameableEntity;
use App\Entity\Traits\EnableableEntity;
use App\Repository\PersonneRepository;
use App\Security\UserPersonneInterface;
use App\Service\Geocoder\GeocodableEntity;
use App\Service\Geocoder\GeocodableInterface;
use App\Validator as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: PersonneRepository::class)]
#[Assert\Personne]
#[Assert\Delete\DeletePersonne(['delete'])]
class Personne implements \Stringable, GeocodableInterface, UserPersonneInterface, PasswordAuthenticatedUserInterface
{
    use BlameableEntity;
    use GeocodableEntity;
    use EnableableEntity;

    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $telephone_mobile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $telephone_fixe = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $civilite = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fonction = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $codePostal = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $commune = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pays = null;

    /**
     * @var Collection<int, Structure>
     */
    #[ORM\ManyToMany(targetEntity: Structure::class, mappedBy: 'personnes')]
    private Collection $structures;

    #[ORM\Column(length: 180, nullable: true)]
    private ?string $username = null;

    #[ORM\ManyToOne(inversedBy: 'personnes')]
    private ?Profil $profil = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $lastLogin = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $password = null;

    /**
     * @var Collection<int, Structure>
     */
    #[ORM\ManyToMany(targetEntity: Structure::class, mappedBy: 'referents')]
    private Collection $referentStructures;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $complementAdresse = null;

    /**
     * @var Collection<int, ContactInterlocuteur>
     */
    #[ORM\OneToMany(targetEntity: ContactInterlocuteur::class, mappedBy: 'personne')]
    private Collection $contactInterlocuteurs;

    /**
     * @var Collection<int, Contact>
     */
    #[ORM\OneToMany(targetEntity: Contact::class, mappedBy: 'auteur')]
    private Collection $auteurContacts;

    /**
     * @var Collection<int, PersonneWidget>
     */
    #[ORM\OneToMany(targetEntity: PersonneWidget::class, mappedBy: 'personne', cascade: ['remove'])]
    #[ORM\OrderBy(['sortable' => 'ASC'])]
    private Collection $personneWidgets;

    #[ORM\Column]
    private ?bool $vip = false;

    #[ORM\ManyToOne(inversedBy: 'personnes')]
    private ?DepartementDomaine $departementDomaine = null;

    /**
     * @var Collection<int, Alerte>
     */
    #[ORM\OneToMany(targetEntity: Alerte::class, mappedBy: 'personne', cascade: ['remove'])]
    private Collection $auteur;

    /**
     * @var Collection<int, Alerte>
     */
    #[ORM\OneToMany(targetEntity: Alerte::class, mappedBy: 'auteur')]
    private Collection $auteurAlertes;

    /**
     * @var Collection<int, Tag>
     */
    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'personnes')]
    private Collection $tags;

    /**
     * @var Collection<int, Artiste>
     */
    #[ORM\ManyToMany(targetEntity: Artiste::class, mappedBy: 'personnes')]
    private Collection $artistes;

    public function __construct()
    {
        $this->structures = new ArrayCollection();
        $this->referentStructures = new ArrayCollection();
        $this->contactInterlocuteurs = new ArrayCollection();
        $this->auteurContacts = new ArrayCollection();
        $this->personneWidgets = new ArrayCollection();
        $this->auteur = new ArrayCollection();
        $this->auteurAlertes = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->artistes = new ArrayCollection();
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = strtoupper($nom);

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephoneMobile(): ?string
    {
        return $this->telephone_mobile;
    }

    public function setTelephoneMobile(?string $telephone_mobile): static
    {
        $this->telephone_mobile = $telephone_mobile;

        return $this;
    }

    public function getTelephoneFixe(): ?string
    {
        return $this->telephone_fixe;
    }

    public function setTelephoneFixe(?string $telephone_fixe): static
    {
        $this->telephone_fixe = $telephone_fixe;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(?string $civilite): static
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getFonction(): ?string
    {
        return $this->fonction;
    }

    public function setFonction(?string $fonction): static
    {
        $this->fonction = $fonction;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(?string $codePostal): static
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    public function getCommune(): ?string
    {
        return $this->commune;
    }

    public function setCommune(?string $commune): static
    {
        $this->commune = $commune;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(?string $pays): static
    {
        $this->pays = $pays;

        return $this;
    }

    public function __toString()
    {
        return (string) trim($this->prenom.' '.$this->nom);
    }

    /**
     * @return Collection<int, Structure>
     */
    public function getStructures(): Collection
    {
        return $this->structures;
    }

    public function addStructure(Structure $structure): static
    {
        if (!$this->structures->contains($structure)) {
            $this->structures->add($structure);
            $structure->addPersonne($this);
        }

        return $this;
    }

    public function removeStructure(Structure $structure): static
    {
        if ($this->structures->removeElement($structure)) {
            $structure->removePersonne($this);
        }

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getProfil(): ?Profil
    {
        return $this->profil;
    }

    public function setProfil(?Profil $profil): static
    {
        $this->profil = $profil;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeInterface
    {
        return $this->lastLogin;
    }

    public function setLastLogin(?\DateTimeInterface $lastLogin): static
    {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function eraseCredentials(): void
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        if ($this->username === null || $this->username === '') {
            return '-';
        }

        return $this->username;
    }

    /**
     * @return string[]
     */
    public function getRoles(): array
    {
        if ($this->profil === null) {
            return [];
        }
        $roles = ['ROLE_USER'];
        $roles = array_merge($roles, $this->profil->getRoles());

        return array_unique($roles);
    }

    /**
     * @return Collection<int, Structure>
     */
    public function getReferentStructures(): Collection
    {
        return $this->referentStructures;
    }

    public function addReferentStructures(Structure $referentStructure): static
    {

src/Form/StructureType.php
<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\Structure;
use App\Entity\Tag;
use App\Entity\TypeStructure;
use App\Form\Type\CustomDateType;
use App\Form\Type\OuiNonType;
use App\Validator\Siret;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StructureType extends AbstractType
{
    public function __construct(private readonly Security $security)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $siretRequired = true;
        if ($builder->getData()->getId()) {
            $siretRequired = false;
        }

        $builder
            ->add('nom', TextType::class, ['label' => 'Nom usuel', 'required' => true])
            ->add('raisonSociale', TextType::class, ['label' => 'Raison sociale', 'required' => true])
            ->add('typeStructures', EntityType::class, ['label' => 'Type de structure',
                'class' => TypeStructure::class,
                'expanded' => true,
                'multiple' => true,
                'attr' => ['class' => 'select-multiple-bordered select-multiple-3cols'],
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->andWhere('u.enabled = true')
                        ->orderBy('u.sortable', 'ASC');
                },
            ])
            ->add('tags', EntityType::class, [
                'label' => 'Tags',
                'expanded' => true,
                'multiple' => true,
                'attr' => ['class' => 'select-multiple-bordered select-multiple-3cols'],
                'class' => Tag::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('t')
                        ->andWhere('t.type = :type')
                        ->setParameter('type', Tag::TYPE_STRUCTURE)
                        ->andWhere('t.enabled = true')
                        ->orderBy('t.sortable', 'ASC');
                },
            ])
            ->add('siret', TextType::class, [
                'label' => 'Siret',
                'required' => false,
                'constraints' => [
                    new Siret(),
                ],
            ])
            ->add('adresse', TextareaType::class, [
                'label' => 'Adresse',
                'required' => false,
                'attr' => ['class' => 'small'],
            ])
            ->add('complementAdresse', TextareaType::class, [
                'label' => 'Complément d\'adresse',
                'required' => false,
                'attr' => ['class' => 'small'],
            ])
            ->add('codePostal', TextType::class, ['label' => 'Code postal', 'required' => false])
            ->add('commune', TextType::class, ['label' => 'Commune', 'required' => false])
            ->add('pays', TextType::class, ['label' => 'Pays', 'required' => false])
            ->add('telephone', TextType::class, ['label' => 'Téléphone', 'required' => false])
            ->add('email', TextType::class, ['label' => 'Email', 'required' => false])

            ->add('datePremierContact', CustomDateType::class, ['label' => 'Date de premier contact', 'required' => false])
            ->add('infosDiverses', TextareaType::class, ['label' => 'Informations diverses', 'required' => false])
            ->add('adminOnly', OuiNonType::class, ['label' => 'Seuls les administrateurs peuvent modifier cette structure'])
            ->add('enabled', OuiNonType::class, ['label' => 'Activé']);

        if (!$this->security->isGranted('ROLE_ADMIN')) {
            $builder->remove('adminOnly');
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Structure::class,
        ]);
    }
}

templates/structure/_delete_form.html.twig
{% if is_granted('DELETE', structure) %}
<form method="post" action="{{ path('app_structure_delete', {'id': structure.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ structure.id) }}">
    <button class="btn btn-sm btn-danger btn-delete">supprimer</button>
</form>
{% endif %}

templates/structure/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn btn-primary btn-sm">enregistrer</button>
{% if structure.id %}
    <a href="{{ path('app_structure_show', {id: structure.id}) }}" class="btn btn-sm btn-primary btn-back">retour</a>
{% else %}
    <a href="{{ path('app_structure_index',) }}" class="btn btn-sm btn-primary btn-back">retour</a>
{% endif %}
{{ form_end(form) }}

templates/structure/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier structure{% endblock %}

{% block body %}
    <h1><picto class="structure-picto"></picto>Modifier structure</h1>

    {{ include('structure/_form.html.twig') }}
    {{ include('structure/_delete_form.html.twig') }}
{% endblock %}

templates/structure/importExcel.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <h1>Importer des structure depuis un fichier <span>Excel</span></h1>
    <p>Vous pouvez charger ci dessous un fichier excel. Le fichier excel doit être composé de 2 colonnes :</p>
    <ul>
        <li>La première contient les numéros de SIRET à importer</li>
        <li>La deuxième (qui est facultative) contient la date de premier contact de la structure</li>
    </ul>
    <p>Les structures seront ensuite créées (si le SIRET est valide). Le nombre max de structures créées est de {{ max }}, vous pouvez passer plusieurs foi sle même fichier, les structure ne seront
        pas doublonnées.</p>
    <div class="form">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary btn-sm">importer</button>
        {{ form_end(form) }}
    </div>
    <br/>
    {% if siretImporter.created|length %}
        <h3>Création :</h3>

        {% if siretImporter.created|length >1 %}
            <p>{{ siretImporter.created |length }} structures ont été créées.</p>
        {% else %}
            <p>1 structure a été créée.</p>
        {% endif %}
        <p>{{ siretImporter.created | join(' , ') }}</p>
    {% endif %}

    {% if siretImporter.invalid|length %}
        <h4>SIRET invalides :</h4>
        <p>Certains numéros de SIRET sont invalides :</p>
        <p>{{ siretImporter.invalid |join(' -- ') }}</p>
    {% endif %}

    {% if siretImporter.exists|length %}
        <h4>Structures Existantes</h4>
        <p>Certaines structures étaient déjà existantes :</p>
        <p>{{ siretImporter.exists |join(' -- ') }}</p>
    {% endif %}
{% endblock %}

templates/structure/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle structure{% endblock %}

{% block body %}
    <h1><picto class="structure-picto"></picto>Nouvelle structure</h1>

    {{ include('structure/_form.html.twig') }}

{% endblock %}

templates/structure/referents.html.twig
<table class="table table-bordered">
    <thead>
    <tr>
        <th class="text-center" title="Référent principal" ><i class="fas fa-crown"></i></th>
        <th>Nom</th>
        <th>Service</th>
        <th>Email</th>
        <th>Téléphone</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for personne in structure.referents %}
        <tr>
            <td class="text-center">
                <a href="{{ path('app_structure_referent_principal', {structure: structure.id, referent: personne.id}) }}"
                   class="{{ personne == structure.referentPrincipal ? "on":"off" }}"
                   title="{{ personne == structure.referentPrincipal ? "Référent principal" : "Référent secondaire" }}"
                   style="text-decoration: none"
                >&nbsp;</a>
            </td>
            <td>
                {% if is_granted('VIEW', personne) %}
                    <a href="{{ path('app_personne_show', {id: personne.id }) }}">{{ personne.nom }} {{ personne.prenom }}</a>
                {% else %}
                    {{ personne.nom }} {{ personne.prenom }}
                {% endif %}
            </td>
            <td>{{ personne.services |join(',') }}</td>
            <td>{{ personne.email }}</td>
            <td>{{ personne.telephoneMobile }}</td>
            <td>
                {% if is_granted('EDIT', structure) %}
                    <a href="{{ path('app_structure_remove_referent', {structure: structure.id, referent: personne.id}) }}"
                       class="btn btn-sm btn-delete btn-danger"
                       onClick="return(confirm('Supprimer le lien entre le référent et la structure ?'))"
                    >suppr. lien référent</a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% if is_granted('EDIT', structure) %}
    <div class="mt-5">
        <div class="autocomplete">
            <label for="personne-autocomplete">Ajouter un référent : </label>
            <input type="text" class="form-control" placeholder="saisissez un nom" id="referent-autocomplete" data-value="" data-url="{{ path('app_structure_referent_autocomplete') }}"/>
            <form action="{{ path('app_structure_add_referent') }}" method="post" id="formAddReferent">
                <input type="hidden" name="structure" value="{{ structure.id }}">
                <input type="hidden" id='inputAddReferent' name="referent" value="">
            </form>
        </div>

    </div>
    <small class="info">La personne doit préalablement avoir été créée <br/> dans l'onglet "Personne" </small>
{% endif %}

templates/structure/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ structure }}{% endblock %}

{% block body %}

    <h1>
        <picto class="structure-picto"></picto>
        Structure <span>{{ structure }}</span></h1>
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <button class="nav-link active" id="nav-structure-tab" data-bs-toggle="tab" data-bs-target="#nav-structure" type="button" role="tab" aria-controls="nav-structure" aria-selected="true">
                Structure
            </button>
            {% if structure.longitude or structure.latitude %}
                <button class="nav-link" id="nav-map-tab" data-bs-toggle="tab" data-bs-target="#nav-map" type="button" role="tab" aria-controls="nav-map" aria-selected="false">
                    Carte
                </button>
            {% endif %}

            <button class="nav-link" id="nav-personnes-tab" data-bs-toggle="tab" data-bs-target="#nav-personnes" type="button" role="tab" aria-controls="nav-personnes" aria-selected="false">
                Personnes de la structure
            </button>

            <button class="nav-link" id="nav-referents-tab" data-bs-toggle="tab" data-bs-target="#nav-referents" type="button" role="tab" aria-controls="nav-referents" aria-selected="false">
                Référents Batard
            </button>
            <button class="nav-link" id="nav-contacts-tab" data-bs-toggle="tab" data-bs-target="#nav-contacts" type="button" role="tab" aria-controls="nav-contacts" aria-selected="false">
                Contacts
            </button>
        </div>
    </nav>

    <div class="tab-content mt-3" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-structure" role="tabpanel" aria-labelledby="nav-structure-tab" tabindex="0">
            <table class="table">
                <tbody>
                <tr>
                    <th>Nom usuel</th>
                    <td>{{ structure.nom }}</td>
                </tr>
                <tr>
                    <th>Raison Sociale</th>
                    <td>{{ structure.raisonSociale }}</td>
                </tr>
                <tr>
                    <th>Type de structure</th>
                    <td>
                        <ul class="list-unstyled">
                            {% for typeStructure in structure.typeStructures %}
                                <li>{{ typeStructure }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>

                <tr>
                    <th>Tags</th>
                    <td>{{ structure.tags | join(', ') }}</td>
                </tr>
                <tr>
                    <th>Adresse</th>
                    <td>
                        {{ structure.adresse | nl2br }}<br>
                        {% if structure.complementAdresse %}
                            {{ structure.complementAdresse | nl2br }}<br>
                        {% endif %}
                        {{ structure.codePostal }} {{ structure.commune }}</td>
                </tr>
                <tr>
                    <th>Téléphone</th>
                    <td>{{ structure.telephone }}</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>{{ structure.email }}</td>
                </tr>
                <tr>
                    <th>Siret</th>
                    <td>{{ structure.siret }}</td>
                </tr>
                <tr>
                    <th>Date premier contact</th>
                    <td>
                        {{ structure.datePremierContact? structure.datePremierContact.format('d/m/Y') }}
                    </td>
                </tr>
                <tr>
                    <th>Informations diverses</th>
                    <td>{{ structure.infosDiverses |nl2br }}</td>
                </tr>
                <tr>
                    <th>Activé</th>
                    <td>{{ structure.enabled ? "Oui" :"Non" }}</td>
                </tr>
                {% if structure.adminOnly %}
                    <tr>
                        <th>Admin</th>
                        <td>Seuls les administrateurs peuvent modifier cette structure</td>
                    </tr>
                {% endif %}

                <tr>
                    <th>Création (fiche structure)</th>
                    <td>{{ structure.createdByAt }}</td>
                </tr>
                <tr>
                    <th>Dernière modification</th>
                    <td>{{ structure.updatedByAt }}</td>
                </tr>
                <tr>
                    <th>Coordonnées GPS</th>
                    <td>{{ structure.latitude }} ; {{ structure.longitude }}</td>
                </tr>
                <tr>
                    <th>Score géocodage</th>
                    <td>{{ structure.scoreGeocode }}</td>
                </tr>
                <tr>
                    <th>Id</th>
                    <td>{{ structure.id }}</td>
                </tr>
                </tbody>
            </table>

            {% if is_granted('EDIT', structure) %}
                <a href="{{ path('app_structure_edit', {'id': structure.id}) }}" class="btn btn-sm btn-primary btn-edit">modifier</a>
                <a href="{{ path('app_structure_geocode', {'id': structure.id}) }}" class="btn btn-sm btn-primary btn-geo">géocoder</a>
                {% if structure.siret %}
                    <a href="{{ path('app_structure_update_from_siret', {'id': structure.id}) }}" class="btn btn-sm btn-primary btn-edit">MAJ depuis SIRET</a>
                {% endif %}
            {% endif %}
            {{ include('structure/_delete_form.html.twig') }}
        </div>

        <div class="tab-pane fade" id="nav-personnes" role="tabpanel" aria-labelledby="nav-personnes-tab" tabindex="0">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Fonction</th>
                    <th>Email</th>
                    <th>Tél. mob</th>
                    <th>Tél. fixe</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for personne in structure.personnes %}
                    <tr>
                        <td>
                            {% if is_granted('VIEW', personne) %}
                                <a href="{{ path('app_personne_show', {id: personne.id }) }}">{{ personne.nom }} {{ personne.prenom }}</a>
                            {% else %}
                                {{ personne.nom }} {{ personne.prenom }}
                            {% endif %}
                        </td>
                        <td>{{ personne.fonction }}</td>
                        <td>{{ personne.email }}</td>
                        <td>{{ personne.telephoneMobile }}</td>
                        <td>{{ personne.telephoneFixe }}</td>
                        <td>
                            {% if is_granted('EDIT', structure) %}
                                <a href="{{ path('app_structure_remove_personne', {structure: structure.id, personne: personne.id}) }}"
                                   class="btn btn-sm btn-delete btn-danger"
                                   onClick="return(confirm('Supprimer le lien entre la personne et la structure ?'))"
                                >suppr. lien</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if is_granted('EDIT', structure) %}
                <div class="mt-5">
                    <div class="autocomplete">
                        <label for="personne-autocomplete">Ajouter une personne : </label>
                        <input type="text" class="form-control" placeholder="saisissez un nom" id="personne-autocomplete" data-value="" data-url="{{ path('app_structure_personne_autocomplete') }}"/>
                        <form action="{{ path('app_structure_add_personne') }}" method="post" id="formAddPersonne">
                            <input type="hidden" name="structure" value="{{ structure.id }}">
                            <input type="hidden" id='inputAddPersonne' name="personne" value="">
                        </form>
                    </div>
                </div>
                <small class="info">La personne doit préalablement avoir été créée <br/> dans l'onglet "Personne" </small>
            {% endif %}
        </div>

        <div class="tab-pane fade" id="nav-referents" role="tabpanel" aria-labelledby="nav-referents-tab" tabindex="0">
            {{ include('structure/referents.html.twig') }}
        </div>

        {% if structure.longitude or structure.latitude %}
            <div class="tab-pane fade" id="nav-map" role="tabpanel" aria-labelledby="nav-map-tab" tabindex="0">
                <div id="map"></div>
            </div>
        {% endif %}

        <div class="tab-pane fade" id="nav-contacts" role="tabpanel" aria-labelledby="nav-contacts-tab" tabindex="0">
            {% if is_granted('ROLE_CONTACT_CREATE') %}
                <a href="{{ path('app_contact_structure_new', {structure: structure.id}) }}" class="btn btn-primary btn-add btn-sm">ajouter</a>
            {% endif %}
            <div class="row mt-2">
                {% for contact in contacts %}
                    {{ include('contact/_contact.html.twig') }}
                {% endfor %}
            </div>
        </div>


    </div>
    <div class="mt-5">
        <a href="{{ path('app_structure_index') }}" class="btn btn-sm btn-primary btn-back">retour</a>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script type="module">
        import {FrontAutoComplete} from 'frontTools';

        document.addEventListener("DOMContentLoaded", function (event) {
            const a = new FrontAutoComplete('personne-autocomplete', function (id) {
                document.getElementById('inputAddPersonne').value = id;
                document.getElementById('formAddPersonne').submit();
            }, 2, 500);

            const b = new FrontAutoComplete('referent-autocomplete', function (id) {
                document.getElementById('inputAddReferent').value = id;
                document.getElementById('formAddReferent').submit();
            }, 2, 500);


            {% if app.request.query.get('tab') is not null %}
            let tab = document.getElementById("nav-{{ app.request.query.get('tab') }}-tab");
            if (tab) {
                tab.click()
            }
            {% endif %}
        });
        {% if structure.longitude or structure.latitude %}
        var icon = L.icon({iconUrl: '/marker-icon.png', iconSize: [25, 41], iconAnchor: [12, 41]});
        var map = L.map('map').setView([{{ structure.latitude }}, {{ structure.longitude }} ], 13);

        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);

        L.marker([{{ structure.latitude }}, {{ structure.longitude }}], {icon: icon}).addTo(map).bindPopup('{{ structure }}')
        document.getElementById('nav-map-tab').addEventListener('click', function () {
            setTimeout(function () {
                map.invalidateSize();
            }, 500);
        })

        setTimeout(function () {
            map.invalidateSize();
        }, 500);
        {% endif %}
    </script>
{% endblock %}